name: scseq
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - _r-mutex=1.0.1
  - absl-py=2.1.0
  - anndata=0.10.6
  - anndata2ri=1.3.1
  - annotated-types=0.6.0
  - anyio=3.7.1
  - appnope=0.1.4
  - argcomplete=3.5.1
  - arpack=3.8.0
  - array-api-compat=1.4.1
  - arrow=1.3.0
  - asttokens=2.4.1
  - backoff=2.2.1
  - beautifulsoup4=4.12.3
  - bioconductor-biobase=2.62.0
  - bioconductor-biocgenerics=0.48.1
  - bioconductor-data-packages=20231203
  - bioconductor-delayedarray=0.28.0
  - bioconductor-genomeinfodb=1.38.1
  - bioconductor-genomeinfodbdata=1.2.11
  - bioconductor-genomicranges=1.54.1
  - bioconductor-iranges=2.36.0
  - bioconductor-matrixgenerics=1.14.0
  - bioconductor-s4arrays=1.2.0
  - bioconductor-s4vectors=0.40.2
  - bioconductor-singlecellexperiment=1.24.0
  - bioconductor-sparsearray=1.2.2
  - bioconductor-summarizedexperiment=1.32.0
  - bioconductor-xvector=0.42.0
  - bioconductor-zlibbioc=1.48.0
  - blessed=1.19.1
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bwidget=1.9.14
  - bzip2=1.0.8
  - c-ares=1.27.0
  - ca-certificates=2024.8.30
  - cachecontrol=0.14.0
  - cachecontrol-with-filecache=0.14.0
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.0
  - cctools_osx-64=986
  - celltypist=1.6.2
  - certifi=2024.8.30
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - chex=0.1.83
  - clang=17.0.6
  - clang-17=17.0.6
  - clang_impl_osx-64=17.0.6
  - clang_osx-64=17.0.6
  - clangxx=17.0.6
  - clangxx_impl_osx-64=17.0.6
  - clangxx_osx-64=17.0.6
  - cleo=2.1.0
  - click=8.1.7
  - colorama=0.4.6
  - comm=0.2.2
  - compiler-rt=17.0.6
  - compiler-rt_osx-64=17.0.6
  - contextlib2=21.6.0
  - contourpy=1.2.0
  - crashtest=0.4.1
  - croniter=1.4.1
  - curl=8.5.0
  - cycler=0.12.1
  - dateutils=0.6.12
  - debugpy=1.8.5
  - decorator=5.1.1
  - deepdiff=6.7.1
  - distlib=0.3.8
  - dm-tree=0.1.8
  - docrep=0.3.2
  - dulwich=0.21.7
  - dunamai=1.19.2
  - et_xmlfile=1.1.0
  - exceptiongroup=1.2.0
  - executing=2.1.0
  - expat=2.5.0
  - fastapi=0.110.0
  - filelock=3.13.1
  - flax=0.6.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.49.0
  - freetype=2.12.1
  - fribidi=1.0.10
  - fsspec=2024.2.0
  - get-annotations=0.1.2
  - get_version=3.5.5
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - gfortran_impl_osx-64=12.3.0
  - gfortran_osx-64=12.3.0
  - git=2.43.0
  - glpk=5.0
  - gmp=6.3.0
  - gmpy2=2.1.2
  - graphite2=1.3.13
  - h11=0.14.0
  - h5py=3.10.0
  - harfbuzz=8.3.0
  - hdf5=1.14.3
  - icu=73.2
  - idna=3.6
  - igraph=0.10.10
  - importlib-metadata=7.0.1
  - importlib_metadata=7.0.1
  - inquirer=3.1.4
  - ipykernel=6.29.5
  - ipython=8.29.0
  - isl=0.26
  - itsdangerous=2.1.2
  - jaraco.classes=3.3.1
  - jax=0.4.13
  - jaxlib=0.4.12
  - jedi=0.19.1
  - jinja2=3.1.3
  - joblib=1.3.2
  - jq=1.7.1
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - keyring=24.3.1
  - kiwisolver=1.4.5
  - krb5=1.21.2
  - lcms2=2.16
  - ld64_osx-64=711
  - legacy-api-wrap=1.4
  - leidenalg=0.10.2
  - lerc=4.0.0
  - libabseil=20230125.3
  - libaec=1.1.2
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang-cpp17=17.0.6
  - libcurl=8.5.0
  - libcxx=16.0.6
  - libdeflate=1.19
  - libedit=3.1.20191231
  - libev=4.33
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libgfortran=5.0.0
  - libgfortran-devel_osx-64=12.3.0
  - libgfortran5=13.2.0
  - libglib=2.78.4
  - libgrpc=1.56.2
  - libhwloc=2.9.3
  - libiconv=1.17
  - libintl=0.22.5
  - libintl-devel=0.22.5
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libleidenalg=0.11.1
  - libllvm14=14.0.6
  - libllvm17=17.0.6
  - libnghttp2=1.58.0
  - libopenblas=0.3.26
  - libpng=1.6.43
  - libprotobuf=4.23.3
  - libsodium=1.0.18
  - libsqlite=3.45.1
  - libssh2=1.11.0
  - libtiff=4.6.0
  - libuv=1.47.0
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxml2=2.12.5
  - libzlib=1.2.13
  - lightning=2.0.9.post0
  - lightning-cloud=0.5.39
  - lightning-utilities=0.10.1
  - llvm-openmp=17.0.6
  - llvm-tools=17.0.6
  - llvmlite=0.42.0
  - make=4.3
  - markdown-it-py=3.0.0
  - markupsafe=2.1.5
  - matplotlib-base=3.8.3
  - matplotlib-inline=0.1.7
  - mdurl=0.1.2
  - mkl=2022.2.1
  - ml-collections=0.1.1
  - ml_dtypes=0.3.2
  - more-itertools=10.2.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - msgpack-python=1.0.7
  - mudata=0.2.3
  - multipledispatch=0.6.0
  - munkres=1.1.4
  - natsort=8.4.0
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - networkx=3.2.1
  - numba=0.59.0
  - numpy=1.26.4
  - numpyro=0.13.2
  - oniguruma=6.9.9
  - openjpeg=2.5.2
  - openpyxl=3.1.2
  - openssl=3.4.0
  - opt_einsum=3.3.0
  - optax=0.1.9
  - ordered-set=4.1.0
  - orjson=3.9.15
  - packaging=23.2
  - pandoc=3.5
  - pango=1.52.1
  - parso=0.8.4
  - patsy=0.5.6
  - pcre2=10.42
  - perl=5.32.1
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.2.0
  - pip=24.0
  - pixman=0.43.4
  - pkginfo=1.10.0
  - platformdirs=4.2.0
  - poetry=1.8.2
  - poetry-core=1.9.0
  - poetry-plugin-export=1.6.0
  - prompt-toolkit=3.0.48
  - psutil=5.9.8
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycparser=2.21
  - pydantic=2.1.1
  - pydantic-core=2.4.0
  - pygments=2.17.2
  - pyjwt=2.8.0
  - pyparsing=3.1.1
  - pyproject_hooks=1.0.0
  - pyro-api=0.1.2
  - pyro-ppl=1.9.0
  - pysocks=1.7.1
  - python=3.11.8
  - python-annoy=1.17.2
  - python-build=1.1.1
  - python-dateutil=2.9.0
  - python-editor=1.0.4
  - python-fastjsonschema=2.19.1
  - python-igraph=0.11.4
  - python-installer=0.7.0
  - python-multipart=0.0.9
  - python-tzdata=2024.1
  - python_abi=3.11
  - pytorch=2.0.0
  - pytorch-lightning=2.1.3
  - pytz=2024.1
  - pyyaml=6.0.1
  - pyzmq=26.1.1
  - r-abind=1.4_5
  - r-askpass=1.2.1
  - r-assertthat=0.2.1
  - r-backports=1.5.0
  - r-base=4.3.3
  - r-base64enc=0.1_3
  - r-bh=1.84.0_0
  - r-bit=4.5.0
  - r-bit64=4.5.2
  - r-bitops=1.0_9
  - r-blob=1.2.4
  - r-broom=1.0.7
  - r-bslib=0.8.0
  - r-cachem=1.1.0
  - r-callr=3.7.6
  - r-catools=1.18.2
  - r-cellranger=1.1.0
  - r-cli=3.6.3
  - r-clipr=0.8.0
  - r-cluster=2.1.6
  - r-codetools=0.2_20
  - r-colorspace=2.1_1
  - r-commonmark=1.9.2
  - r-conflicted=1.2.0
  - r-cowplot=1.1.3
  - r-cpp11=0.5.0
  - r-crayon=1.5.3
  - r-crosstalk=1.2.1
  - r-curl=5.2.1
  - r-data.table=1.15.2
  - r-dbi=1.2.3
  - r-dbplyr=2.5.0
  - r-deldir=2.0_4
  - r-digest=0.6.37
  - r-dotcall64=1.2
  - r-dplyr=1.1.4
  - r-dqrng=0.3.2
  - r-dtplyr=1.3.1
  - r-ellipsis=0.3.2
  - r-evaluate=1.0.1
  - r-fansi=1.0.6
  - r-farver=2.1.2
  - r-fastdummies=1.7.4
  - r-fastmap=1.2.0
  - r-fitdistrplus=1.2_1
  - r-fnn=1.1.4
  - r-fontawesome=0.5.2
  - r-forcats=1.0.0
  - r-fs=1.6.4
  - r-future=1.34.0
  - r-future.apply=1.11.2
  - r-gargle=1.5.2
  - r-generics=0.1.3
  - r-ggplot2=3.5.1
  - r-ggrepel=0.9.5
  - r-ggridges=0.5.6
  - r-globals=0.16.3
  - r-glue=1.8.0
  - r-goftest=1.2_3
  - r-googledrive=2.1.1
  - r-googlesheets4=1.1.1
  - r-gplots=3.2.0
  - r-gridextra=2.3
  - r-gtable=0.3.6
  - r-gtools=3.9.5
  - r-haven=2.5.4
  - r-here=1.0.1
  - r-hexbin=1.28.4
  - r-highr=0.11
  - r-hms=1.1.3
  - r-htmltools=0.5.8.1
  - r-htmlwidgets=1.6.4
  - r-httpuv=1.6.15
  - r-httr=1.4.7
  - r-ica=1.0_3
  - r-ids=1.0.1
  - r-igraph=2.0.2
  - r-irlba=2.3.5.1
  - r-isoband=0.2.7
  - r-jquerylib=0.1.4
  - r-jsonlite=1.8.9
  - r-kernsmooth=2.23_24
  - r-knitr=1.48
  - r-labeling=0.4.3
  - r-later=1.3.2
  - r-lattice=0.22_6
  - r-lazyeval=0.2.2
  - r-leiden=0.4.3.1
  - r-lifecycle=1.0.4
  - r-listenv=0.9.1
  - r-lmtest=0.9_40
  - r-lubridate=1.9.3
  - r-magrittr=2.0.3
  - r-mass=7.3_60.0.1
  - r-matrix=1.6_5
  - r-matrixstats=1.4.1
  - r-memoise=2.0.1
  - r-mgcv=1.9_1
  - r-mime=0.12
  - r-miniui=0.1.1.1
  - r-modelr=0.1.11
  - r-munsell=0.5.1
  - r-nlme=3.1_165
  - r-openssl=2.2.2
  - r-parallelly=1.38.0
  - r-patchwork=1.3.0
  - r-pbapply=1.7_2
  - r-pillar=1.9.0
  - r-pkgconfig=2.0.3
  - r-plotly=4.10.4
  - r-plyr=1.8.9
  - r-png=0.1_8
  - r-polyclip=1.10_7
  - r-prettyunits=1.2.0
  - r-processx=3.8.4
  - r-progress=1.2.3
  - r-progressr=0.15.0
  - r-promises=1.3.0
  - r-ps=1.8.1
  - r-purrr=1.0.2
  - r-r6=2.5.1
  - r-ragg=1.3.2
  - r-rann=2.6.1
  - r-rappdirs=0.3.3
  - r-rcolorbrewer=1.1_3
  - r-rcpp=1.0.13
  - r-rcppannoy=0.0.22
  - r-rcpparmadillo=14.0.0_1
  - r-rcppeigen=0.3.4.0.1
  - r-rcpphnsw=0.6.0
  - r-rcppprogress=0.4.2
  - r-rcpptoml=0.2.2
  - r-rcurl=1.98_1.14
  - r-readr=2.1.5
  - r-readxl=1.4.3
  - r-rematch=2.0.0
  - r-rematch2=2.1.2
  - r-reprex=2.1.1
  - r-reshape2=1.4.4
  - r-reticulate=1.38.0
  - r-rlang=1.1.4
  - r-rmarkdown=2.29
  - r-rocr=1.0_11
  - r-rprojroot=2.0.4
  - r-rspectra=0.16_2
  - r-rstudioapi=0.17.1
  - r-rtsne=0.17
  - r-rvest=1.0.4
  - r-sass=0.4.9
  - r-scales=1.3.0
  - r-scattermore=1.2
  - r-sctransform=0.4.1
  - r-selectr=0.4_2
  - r-seurat=5.1.0
  - r-seuratobject=5.0.2
  - r-shiny=1.9.1
  - r-sitmo=2.0.2
  - r-sourcetools=0.1.7_1
  - r-sp=2.1_4
  - r-spam=2.10_0
  - r-spatstat.data=3.1_2
  - r-spatstat.explore=3.2_6
  - r-spatstat.geom=3.2_9
  - r-spatstat.random=3.2_3
  - r-spatstat.sparse=3.1_0
  - r-spatstat.utils=3.1_1
  - r-stringi=1.8.4
  - r-stringr=1.5.1
  - r-survival=3.7_0
  - r-sys=3.4.3
  - r-systemfonts=1.1.0
  - r-tensor=1.5
  - r-textshaping=0.3.7
  - r-tibble=3.2.1
  - r-tidyr=1.3.1
  - r-tidyselect=1.2.1
  - r-tidyverse=2.0.0
  - r-timechange=0.3.0
  - r-tinytex=0.54
  - r-tzdb=0.4.0
  - r-utf8=1.2.4
  - r-uuid=1.2_1
  - r-uwot=0.1.16
  - r-vctrs=0.6.5
  - r-viridislite=0.4.2
  - r-vroom=1.6.5
  - r-withr=3.0.2
  - r-xfun=0.47
  - r-xml2=1.3.6
  - r-xtable=1.8_4
  - r-yaml=2.3.10
  - r-zoo=1.8_12
  - rapidfuzz=3.6.1
  - re2=2023.03.02
  - readchar=4.0.5
  - readline=8.2
  - requests=2.31.0
  - requests-toolbelt=1.0.0
  - rich=13.7.1
  - rpy2=3.5.11
  - scikit-learn=1.4.1.post1
  - scipy=1.12.0
  - scvi-tools=1.1.2
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - session-info=1.0.0
  - setuptools=69.1.1
  - shellingham=1.5.4
  - sigtool=0.1.3
  - simplegeneric=0.8.1
  - six=1.16.0
  - sleef=3.5.1
  - sniffio=1.3.1
  - soupsieve=2.5
  - sparse=0.15.1
  - stack_data=0.6.2
  - starlette=0.36.3
  - starsessions=1.3.0
  - statsmodels=0.14.1
  - stdlib-list=0.10.0
  - sympy=1.12
  - tapi=1100.0.11
  - tbb=2021.11.0
  - texttable=1.7.0
  - threadpoolctl=3.3.0
  - tk=8.6.13
  - tktable=2.10
  - toml=0.10.2
  - tomli=2.0.1
  - tomlkit=0.12.4
  - toolz=0.12.1
  - torchmetrics=1.2.1
  - tornado=6.4.1
  - tqdm=4.66.2
  - traitlets=5.14.1
  - trove-classifiers=2024.3.3
  - types-python-dateutil=2.8.19.20240106
  - typing-extensions=4.10.0
  - typing_extensions=4.10.0
  - tzdata=2024a
  - tzlocal=5.2
  - umap-learn=0.5.5
  - urllib3=2.2.1
  - uvicorn=0.27.1
  - virtualenv=20.25.1
  - wcwidth=0.2.13
  - websocket-client=1.7.0
  - websockets=12.0
  - wheel=0.42.0
  - xarray=2024.2.0
  - xattr=1.1.0
  - xlrd=1.2.0
  - xmltodict=0.14.2
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yaml=0.2.5
  - yq=3.4.3
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - deprecated==1.2.14
      - pandas==1.5.3
      - pooch==1.8.1
      - pydot==2.0.0
      - pynndescent==0.5.11
      - scanpy==1.9.8
      - scib==1.1.4
      - scikit-misc==0.3.1
      - wrapt==1.16.0
