name: scseq-cuda
channels:
  - genomedk
  - pytorch
  - nvidia
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _r-mutex=1.0.1
  - anndata=0.11.4
  - anndata2ri=1.3.2
  - anyio=4.9.0
  - aom=3.6.1
  - argcomplete=3.6.2
  - argon2-cffi=25.1.0
  - argon2-cffi-bindings=21.2.0
  - arpack=3.9.1
  - array-api-compat=1.12.0
  - arrow=1.3.0
  - asttokens=3.0.0
  - async-lru=2.0.5
  - attrs=25.3.0
  - babel=2.17.0
  - beautifulsoup4=4.13.4
  - binutils_impl_linux-64=2.43
  - bioconductor-biobase=2.62.0
  - bioconductor-biocgenerics=0.48.1
  - bioconductor-biocneighbors=1.20.0
  - bioconductor-biocparallel=1.36.0
  - bioconductor-data-packages=20250401
  - bioconductor-delayedarray=0.28.0
  - bioconductor-genomeinfodb=1.38.1
  - bioconductor-genomeinfodbdata=1.2.11
  - bioconductor-genomicranges=1.54.1
  - bioconductor-iranges=2.36.0
  - bioconductor-matrixgenerics=1.14.0
  - bioconductor-s4arrays=1.2.0
  - bioconductor-s4vectors=0.40.2
  - bioconductor-singlecellexperiment=1.24.0
  - bioconductor-sparsearray=1.2.2
  - bioconductor-summarizedexperiment=1.32.0
  - bioconductor-ucell=2.6.2
  - bioconductor-xvector=0.42.0
  - bioconductor-zlibbioc=1.48.0
  - blas=1.0
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bwidget=1.10.1
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.6.15
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.4
  - celltypist=1.7.1
  - certifi=2025.6.15
  - cffi=1.17.1
  - charset-normalizer=3.4.2
  - click=8.2.1
  - colorama=0.4.6
  - comm=0.2.2
  - contourpy=1.3.2
  - cpython=3.11.13
  - cuda-cccl_linux-64=12.6.77
  - cuda-crt-dev_linux-64=12.6.85
  - cuda-cudart=12.1.105
  - cuda-cudart-dev_linux-64=12.6.77
  - cuda-cudart-static_linux-64=12.6.77
  - cuda-cudart_linux-64=12.6.77
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.6.77
  - cuda-runtime=12.1.0
  - cuda-version=12.6
  - curl=8.14.1
  - cycler=0.12.1
  - debugpy=1.8.14
  - decorator=5.2.1
  - defusedxml=0.7.1
  - dunamai=1.23.1
  - et_xmlfile=2.0.0
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - ffmpeg=4.4.2
  - filelock=3.18.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.58.4
  - fqdn=1.5.1
  - freetype=2.13.3
  - fribidi=1.0.10
  - gcc_impl_linux-64=13.4.0
  - get_version=3.5.5
  - gfortran_impl_linux-64=13.4.0
  - giflib=5.2.2
  - git=2.49.0
  - glpk=5.0
  - gmp=6.3.0
  - gmpy2=2.2.1
  - gnutls=3.7.9
  - graphite2=1.3.14
  - gsl=2.7
  - gxx_impl_linux-64=13.4.0
  - h11=0.16.0
  - h2=4.2.0
  - h5py=3.14.0
  - harfbuzz=11.2.1
  - hdf5=1.14.6
  - hpack=4.1.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - igraph=0.10.16
  - importlib-metadata=8.7.0
  - importlib_resources=6.5.2
  - intel-openmp=2022.0.1
  - ipykernel=6.29.5
  - ipython=9.3.0
  - ipython_pygments_lexers=1.1.1
  - ipywidgets=8.1.7
  - isoduration=20.11.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.5.1
  - jq=1.8.0
  - json5=0.12.0
  - jsonpointer=3.0.0
  - jsonschema=4.24.0
  - jsonschema-specifications=2025.4.1
  - jsonschema-with-format-nongpl=4.24.0
  - jupyter=1.1.1
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_console=6.6.3
  - jupyter_core=5.8.1
  - jupyter_events=0.12.0
  - jupyter_server=2.16.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.4.3
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.15
  - kernel-headers_linux-64=3.10.0
  - keyutils=1.6.1
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lame=3.100
  - lcms2=2.17
  - ld_impl_linux-64=2.43
  - legacy-api-wrap=1.4.1
  - leidenalg=0.10.2
  - lerc=4.0.0
  - libaec=1.1.4
  - libasprintf=0.24.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcublas=12.1.0.26
  - libcublas-dev=12.1.0.26
  - libcufft=11.0.2.4
  - libcufft-dev=11.0.2.4
  - libcufile=1.11.1.6
  - libcurand=10.3.7.77
  - libcurand-dev=10.3.7.77
  - libcurl=8.14.1
  - libcusolver=11.4.4.55
  - libcusolver-dev=11.4.4.55
  - libcusparse=12.0.2.55
  - libcusparse-dev=12.0.2.55
  - libdeflate=1.24
  - libdrm=2.4.125
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libev=4.33
  - libexpat=2.7.0
  - libffi=3.4.6
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgcc=15.1.0
  - libgcc-devel_linux-64=13.4.0
  - libgcc-ng=15.1.0
  - libgettextpo=0.24.1
  - libgfortran=15.1.0
  - libgfortran-ng=15.1.0
  - libgfortran5=15.1.0
  - libgl=1.7.0
  - libglib=2.84.2
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.1.0
  - libhwloc=2.11.2
  - libiconv=1.18
  - libidn2=2.3.8
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - libleidenalg=0.11.1
  - liblzma=5.8.1
  - libnghttp2=1.64.0
  - libnpp=12.0.2.50
  - libnsl=2.0.1
  - libnvjitlink=12.1.105
  - libnvjpeg=12.1.1.14
  - libopenblas=0.3.30
  - libpciaccess=0.18
  - libpng=1.6.49
  - libsanitizer=13.4.0
  - libsodium=1.0.20
  - libsqlite=3.50.1
  - libssh2=1.11.1
  - libstdcxx=15.1.0
  - libstdcxx-devel_linux-64=13.4.0
  - libstdcxx-ng=15.1.0
  - libtasn1=4.20.0
  - libtiff=4.7.0
  - libunistring=0.9.10
  - libuuid=2.38.1
  - libuv=1.51.0
  - libva=2.22.0
  - libvpx=1.13.1
  - libwebp=1.5.0
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxml2=2.13.8
  - libzlib=1.3.1
  - llvm-openmp=15.0.7
  - llvmlite=0.44.0
  - make=4.4.1
  - markupsafe=3.0.2
  - matplotlib-base=3.10.3
  - matplotlib-inline=0.1.7
  - mistune=3.1.3
  - mkl=2022.1.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - munkres=1.1.4
  - natsort=8.4.0
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nettle=3.9.1
  - networkx=3.5
  - notebook=7.4.3
  - notebook-shim=0.2.4
  - numba=0.61.2
  - numpy=1.26.4
  - oniguruma=6.9.10
  - openh264=2.3.1
  - openjpeg=2.5.3
  - openpyxl=3.1.5
  - openssl=3.5.0
  - overrides=7.7.0
  - p11-kit=0.24.1
  - packaging=25.0
  - pandas=2.3.0
  - pandoc=3.7.0.2
  - pandocfilters=1.5.0
  - pango=1.56.3
  - parso=0.8.4
  - patsy=1.0.1
  - pcre2=10.45
  - perl=5.32.1
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.2.1
  - pip=25.1.1
  - pixman=0.46.2
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.8
  - prometheus_client=0.22.1
  - prompt-toolkit=3.0.51
  - prompt_toolkit=3.0.51
  - psutil=7.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycparser=2.22
  - pygments=2.19.2
  - pynndescent=0.5.13
  - pyparsing=3.2.3
  - pysocks=1.7.1
  - python=3.11.13
  - python-annoy=1.17.3
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.1
  - python-igraph=0.11.9
  - python-json-logger=2.0.7
  - python-tzdata=2025.2
  - python_abi=3.11
  - pytorch=2.5.1
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pytz=2025.2
  - pyyaml=6.0.2
  - pyzmq=27.0.0
  - qhull=2020.2
  - r-abind=1.4_5
  - r-argparse=2.2.5
  - r-askpass=1.2.1
  - r-assertthat=0.2.1
  - r-backports=1.5.0
  - r-base=4.3.3
  - r-base64enc=0.1_3
  - r-bh=1.87.0_1
  - r-bit=4.6.0
  - r-bit64=4.6.0_1
  - r-bitops=1.0_9
  - r-blob=1.2.4
  - r-broom=1.0.8
  - r-bslib=0.9.0
  - r-cachem=1.1.0
  - r-callr=3.7.6
  - r-catools=1.18.3
  - r-cellranger=1.1.0
  - r-checkmate=2.3.2
  - r-cli=3.6.5
  - r-clipr=0.8.0
  - r-cluster=2.1.8.1
  - r-clustree=0.5.1
  - r-codetools=0.2_20
  - r-colorspace=2.1_1
  - r-commonmark=1.9.5
  - r-conflicted=1.2.0
  - r-cowplot=1.1.3
  - r-cpp11=0.5.2
  - r-crayon=1.5.3
  - r-crosstalk=1.2.1
  - r-curl=6.2.2
  - r-data.table=1.17.6
  - r-dbi=1.2.3
  - r-dbplyr=2.5.0
  - r-deldir=2.0_4
  - r-digest=0.6.37
  - r-dotcall64=1.2
  - r-doubletfinder=2.0.4
  - r-dplyr=1.1.4
  - r-dqrng=0.3.2
  - r-dtplyr=1.3.1
  - r-ellipsis=0.3.2
  - r-evaluate=1.0.4
  - r-fansi=1.0.6
  - r-farver=2.1.2
  - r-fastdummies=1.7.5
  - r-fastmap=1.2.0
  - r-fields=16.3.1
  - r-findpython=1.0.9
  - r-fitdistrplus=1.2_2
  - r-fnn=1.1.4.1
  - r-fontawesome=0.5.3
  - r-forcats=1.0.0
  - r-formatr=1.14
  - r-fs=1.6.6
  - r-futile.logger=1.4.3
  - r-futile.options=1.0.1
  - r-future=1.58.0
  - r-future.apply=1.20.0
  - r-gargle=1.5.2
  - r-generics=0.1.4
  - r-ggforce=0.5.0
  - r-ggplot2=3.5.2
  - r-ggraph=2.2.1
  - r-ggrepel=0.9.6
  - r-ggridges=0.5.6
  - r-globals=0.18.0
  - r-glue=1.8.0
  - r-goftest=1.2_3
  - r-googledrive=2.1.1
  - r-googlesheets4=1.1.1
  - r-gplots=3.2.0
  - r-graphlayouts=1.2.2
  - r-gridextra=2.3
  - r-gtable=0.3.6
  - r-gtools=3.9.5
  - r-haven=2.5.4
  - r-here=1.0.1
  - r-hexbin=1.28.5
  - r-hgnchelper=0.8.15
  - r-highr=0.11
  - r-hms=1.1.3
  - r-htmltools=0.5.8.1
  - r-htmlwidgets=1.6.4
  - r-httpuv=1.6.15
  - r-httr=1.4.7
  - r-ica=1.0_3
  - r-ids=1.0.1
  - r-igraph=2.0.3
  - r-irlba=2.3.5.1
  - r-isoband=0.2.7
  - r-jquerylib=0.1.4
  - r-jsonlite=2.0.0
  - r-kernsmooth=2.23_26
  - r-knitr=1.50
  - r-labeling=0.4.3
  - r-lambda.r=1.2.4
  - r-later=1.4.2
  - r-lattice=0.22_7
  - r-lazyeval=0.2.2
  - r-leidenbase=0.1.32
  - r-lifecycle=1.0.4
  - r-listenv=0.9.1
  - r-lmtest=0.9_40
  - r-lubridate=1.9.4
  - r-magrittr=2.0.3
  - r-maps=3.4.3
  - r-mass=7.3_60.0.1
  - r-matrix=1.6_5
  - r-matrixstats=1.5.0
  - r-memoise=2.0.1
  - r-mgcv=1.9_3
  - r-mime=0.13
  - r-miniui=0.1.2
  - r-modelr=0.1.11
  - r-munsell=0.5.1
  - r-nlme=3.1_168
  - r-openssl=2.3.3
  - r-openxlsx=4.2.8
  - r-parallelly=1.45.0
  - r-patchwork=1.3.1
  - r-pbapply=1.7_2
  - r-pillar=1.10.2
  - r-pkgconfig=2.0.3
  - r-plotly=4.11.0
  - r-plyr=1.8.9
  - r-png=0.1_8
  - r-polyclip=1.10_7
  - r-prettyunits=1.2.0
  - r-processx=3.8.6
  - r-progress=1.2.3
  - r-progressr=0.15.1
  - r-promises=1.3.2
  - r-ps=1.9.1
  - r-purrr=1.0.4
  - r-r6=2.6.1
  - r-ragg=1.4.0
  - r-rann=2.6.2
  - r-rappdirs=0.3.3
  - r-rcolorbrewer=1.1_3
  - r-rcpp=1.0.14
  - r-rcppannoy=0.0.22
  - r-rcpparmadillo=14.4.2_1
  - r-rcppeigen=0.3.4.0.2
  - r-rcpphnsw=0.6.0
  - r-rcppprogress=0.4.2
  - r-rcpptoml=0.2.3
  - r-rcurl=1.98_1.16
  - r-readr=2.1.5
  - r-readxl=1.4.5
  - r-rematch=2.0.0
  - r-rematch2=2.1.2
  - r-reprex=2.1.1
  - r-reshape2=1.4.4
  - r-reticulate=1.42.0
  - r-rlang=1.1.6
  - r-rmarkdown=2.29
  - r-rocr=1.0_11
  - r-rprojroot=2.0.4
  - r-rspectra=0.16_2
  - r-rstudioapi=0.17.1
  - r-rtsne=0.17
  - r-rvest=1.0.4
  - r-sass=0.4.10
  - r-scales=1.4.0
  - r-scattermore=1.2
  - r-sctransform=0.4.2
  - r-selectr=0.4_2
  - r-seurat=5.3.0
  - r-seuratobject=5.1.0
  - r-shiny=1.11.0
  - r-sitmo=2.0.2
  - r-snow=0.4_4
  - r-sourcetools=0.1.7_1
  - r-sp=2.2_0
  - r-spam=2.11_1
  - r-spatstat.data=3.1_6
  - r-spatstat.explore=3.4_3
  - r-spatstat.geom=3.4_1
  - r-spatstat.random=3.4_1
  - r-spatstat.sparse=3.1_0
  - r-spatstat.univar=3.1_3
  - r-spatstat.utils=3.1_4
  - r-splitstackshape=1.4.8
  - r-stringi=1.8.7
  - r-stringr=1.5.1
  - r-survival=3.8_3
  - r-sys=3.4.3
  - r-systemfonts=1.2.3
  - r-tensor=1.5.1
  - r-textshaping=1.0.1
  - r-tibble=3.3.0
  - r-tidygraph=1.3.0
  - r-tidyr=1.3.1
  - r-tidyselect=1.2.1
  - r-tidyverse=2.0.0
  - r-timechange=0.3.0
  - r-tinytex=0.57
  - r-tweenr=2.0.3
  - r-tzdb=0.5.0
  - r-utf8=1.2.6
  - r-uuid=1.2_1
  - r-uwot=0.2.3
  - r-vctrs=0.6.5
  - r-viridis=0.6.5
  - r-viridislite=0.4.2
  - r-vroom=1.6.5
  - r-withr=3.0.2
  - r-xfun=0.52
  - r-xml2=1.3.8
  - r-xtable=1.8_4
  - r-yaml=2.3.10
  - r-zip=2.3.3
  - r-zoo=1.8_14
  - readline=8.2
  - referencing=0.36.2
  - requests=2.32.4
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.25.1
  - rpy2=3.5.11
  - scanpy=1.11.2
  - scikit-learn=1.7.0
  - scikit-misc=0.1.4
  - scipy=1.15.2
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - sed=4.9
  - send2trash=1.8.3
  - session-info2=0.1.2
  - setuptools=80.9.0
  - simplegeneric=0.8.1
  - six=1.17.0
  - sniffio=1.3.1
  - soupsieve=2.7
  - stack_data=0.6.3
  - statsmodels=0.14.4
  - svt-av1=1.4.1
  - sysroot_linux-64=2.17
  - tbb=2022.1.0
  - terminado=0.18.1
  - texttable=1.7.0
  - threadpoolctl=3.6.0
  - tinycss2=1.4.0
  - tk=8.6.13
  - tktable=2.10
  - toml=0.10.2
  - tomli=2.2.1
  - tomlkit=0.13.3
  - torchaudio=2.5.1
  - torchtriton=3.1.0
  - torchvision=0.20.1
  - tornado=6.5.1
  - tqdm=4.67.1
  - traitlets=5.14.3
  - types-python-dateutil=2.9.0.20250516
  - typing-extensions=4.14.0
  - typing_extensions=4.14.0
  - typing_utils=0.1.0
  - tzdata=2025b
  - tzlocal=5.3
  - umap-learn=0.5.7
  - unicodedata2=16.0.0
  - uri-template=1.3.0
  - urllib3=2.5.0
  - wayland=1.23.1
  - wayland-protocols=1.45
  - wcwidth=0.2.13
  - webcolors=24.11.1
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.45.1
  - widgetsnbextension=4.0.14
  - x264=1!164.3095
  - x265=3.5
  - xmltodict=0.14.2
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxrender=0.9.12
  - xorg-libxt=1.3.1
  - yaml=0.2.5
  - yq=3.4.3
  - zeromq=4.3.5
  - zipp=3.23.0
  - zstandard=0.23.0
  - zstd=1.5.7
  - pip:
      - absl-py==2.3.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.13
      - aiosignal==1.3.2
      - chex==0.1.89
      - docrep==0.3.2
      - etils==1.12.2
      - flax==0.10.6
      - frozenlist==1.7.0
      - fsspec==2025.5.1
      - grpcio==1.73.0
      - humanize==4.12.3
      - jax==0.5.3
      - jax-cuda12-pjrt==0.5.3
      - jax-cuda12-plugin==0.5.3
      - jaxlib==0.5.3
      - lightning==2.5.2
      - lightning-utilities==0.14.3
      - markdown==3.8.2
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - ml-collections==1.1.0
      - ml-dtypes==0.5.1
      - msgpack==1.1.1
      - mudata==0.3.2
      - multidict==6.5.1
      - multipledispatch==1.0.0
      - numpyro==0.18.0
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvcc-cu12==12.9.86
      - nvidia-cuda-runtime-cu12==12.9.79
      - nvidia-cudnn-cu12==9.5.0.50
      - nvidia-cufft-cu12==11.4.1.4
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.10.65
      - nvidia-nccl-cu12==2.27.3
      - nvidia-nvjitlink-cu12==12.9.86
      - opt-einsum==3.4.0
      - optax==0.2.5
      - orbax-checkpoint==0.11.16
      - propcache==0.3.2
      - protobuf==6.31.1
      - pyro-api==0.1.2
      - pyro-ppl==1.9.1
      - pytorch-lightning==2.5.2
      - rich==14.0.0
      - scvi-tools==1.3.1.post1
      - simplejson==3.20.1
      - sparse==0.17.0
      - sympy==1.13.1
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorstore==0.1.75
      - toolz==1.0.0
      - torchmetrics==1.7.3
      - treescope==0.1.9
      - werkzeug==3.1.3
      - xarray==2025.6.1
      - yarl==1.20.1
