name: scseq
channels:
  - genomedk
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _r-mutex=1.0.1
  - absl-py=2.1.0
  - anndata=0.10.9
  - anndata2ri=1.3.2
  - anyio=4.6.2.post1
  - aom=3.9.1
  - argcomplete=3.5.1
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arpack=3.9.1
  - array-api-compat=1.9.1
  - arrow=1.3.0
  - asttokens=2.4.1
  - async-lru=2.0.4
  - attrs=24.2.0
  - babel=2.14.0
  - beautifulsoup4=4.12.3
  - binutils_impl_linux-64=2.43
  - bioconductor-biobase=2.62.0
  - bioconductor-biocgenerics=0.48.1
  - bioconductor-biocneighbors=1.20.0
  - bioconductor-biocparallel=1.36.0
  - bioconductor-data-packages=20231203
  - bioconductor-delayedarray=0.28.0
  - bioconductor-genomeinfodb=1.38.1
  - bioconductor-genomeinfodbdata=1.2.11
  - bioconductor-genomicranges=1.54.1
  - bioconductor-iranges=2.36.0
  - bioconductor-matrixgenerics=1.14.0
  - bioconductor-s4arrays=1.2.0
  - bioconductor-s4vectors=0.40.2
  - bioconductor-singlecellexperiment=1.24.0
  - bioconductor-sparsearray=1.2.2
  - bioconductor-summarizedexperiment=1.32.0
  - bioconductor-ucell=2.6.2
  - bioconductor-xvector=0.42.0
  - bioconductor-zlibbioc=1.48.0
  - bleach=6.2.0
  - blosc=1.21.6
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bwidget=1.9.14
  - bzip2=1.0.8
  - c-ares=1.32.3
  - ca-certificates=2024.8.30
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.0
  - celltypist=1.6.3
  - certifi=2024.8.30
  - cffi=1.17.1
  - charset-normalizer=3.4.0
  - chex=0.1.87
  - click=8.1.7
  - colorama=0.4.6
  - comm=0.2.2
  - contextlib2=21.6.0
  - contourpy=1.3.0
  - cpython=3.11.10
  - curl=8.10.1
  - cycler=0.12.1
  - dav1d=1.2.1
  - debugpy=1.8.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - docrep=0.3.2
  - dunamai=1.22.0
  - entrypoints=0.4
  - et_xmlfile=2.0.0
  - etils=1.10.0
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - filelock=3.16.1
  - flax=0.10.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.54.1
  - fqdn=1.5.1
  - freetype=2.12.1
  - fribidi=1.0.10
  - fsspec=2024.10.0
  - gcc_impl_linux-64=14.2.0
  - get-annotations=0.1.2
  - get_version=3.5.5
  - gfortran_impl_linux-64=14.2.0
  - git=2.47.0
  - glpk=5.0
  - gmp=6.3.0
  - gmpy2=2.1.5
  - graphite2=1.3.13
  - grpcio=1.62.2
  - gsl=2.7
  - gxx_impl_linux-64=14.2.0
  - h11=0.14.0
  - h2=4.1.0
  - h5py=3.12.1
  - harfbuzz=9.0.0
  - hdf5=1.14.3
  - hpack=4.0.0
  - httpcore=1.0.6
  - httpx=0.27.2
  - hyperframe=6.0.1
  - icu=75.1
  - idna=3.10
  - igraph=0.10.13
  - importlib-metadata=8.5.0
  - importlib_resources=6.4.5
  - ipykernel=6.29.5
  - ipython=8.29.0
  - ipython_genutils=0.2.0
  - ipywidgets=8.1.5
  - isoduration=20.11.0
  - jax=0.4.31
  - jaxlib=0.4.31
  - jedi=0.19.1
  - jinja2=3.1.4
  - joblib=1.4.2
  - jq=1.7.1
  - json5=0.9.25
  - jsonpointer=3.0.0
  - jsonschema=4.23.0
  - jsonschema-specifications=2024.10.1
  - jsonschema-with-format-nongpl=4.23.0
  - jupyter=1.1.1
  - jupyter-lsp=2.2.5
  - jupyter_client=7.4.9
  - jupyter_console=6.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_server=2.14.2
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.3.0
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.13
  - kernel-headers_linux-64=3.10.0
  - keyutils=1.6.1
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lcms2=2.16
  - ld_impl_linux-64=2.43
  - legacy-api-wrap=1.4
  - leidenalg=0.10.2
  - lerc=4.0.0
  - libabseil=20240116.2
  - libaec=1.1.3
  - libavif16=1.1.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcurl=8.10.1
  - libdeflate=1.22
  - libedit=3.1.20191231
  - libev=4.33
  - libexpat=2.6.3
  - libffi=3.4.2
  - libgcc=14.2.0
  - libgcc-devel_linux-64=14.2.0
  - libgcc-ng=14.2.0
  - libgfortran=14.2.0
  - libgfortran-ng=14.2.0
  - libgfortran5=14.2.0
  - libglib=2.82.2
  - libgomp=14.2.0
  - libgrpc=1.62.2
  - libhwloc=2.11.1
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libleidenalg=0.11.1
  - libllvm14=14.0.6
  - libnghttp2=1.64.0
  - libnsl=2.0.1
  - libopenblas=0.3.28
  - libpng=1.6.44
  - libprotobuf=4.25.3
  - libre2-11=2023.09.01
  - libsanitizer=14.2.0
  - libsodium=1.0.20
  - libsqlite=3.47.0
  - libssh2=1.11.0
  - libstdcxx=14.2.0
  - libstdcxx-devel_linux-64=14.2.0
  - libstdcxx-ng=14.2.0
  - libtiff=4.7.0
  - libtorch=2.4.1
  - libuuid=2.38.1
  - libuv=1.49.2
  - libwebp-base=1.4.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxml2=2.13.4
  - libzlib=1.3.1
  - lightning=2.4.0
  - lightning-utilities=0.11.8
  - llvmlite=0.43.0
  - lz4-c=1.9.4
  - make=4.4.1
  - markdown=3.6
  - markdown-it-py=3.0.0
  - markupsafe=3.0.2
  - matplotlib-base=3.9.2
  - matplotlib-inline=0.1.7
  - mdurl=0.1.2
  - mistune=3.0.2
  - ml-collections=0.1.1
  - ml_dtypes=0.5.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - msgpack-python=1.1.0
  - mudata=0.3.1
  - multipledispatch=0.6.0
  - munkres=1.1.4
  - natsort=8.4.0
  - nbclassic=1.1.0
  - nbclient=0.10.0
  - nbconvert-core=7.16.4
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.4.2
  - nomkl=1.0
  - notebook=6.5.7
  - notebook-shim=0.2.4
  - numba=0.60.0
  - numpy=1.26.4
  - numpyro=0.15.3
  - oniguruma=6.9.9
  - openjpeg=2.5.2
  - openpyxl=3.1.5
  - openssl=3.3.2
  - opt-einsum=3.4.0
  - opt_einsum=3.4.0
  - optax=0.2.3
  - orbax-checkpoint=0.4.4
  - overrides=7.7.0
  - packaging=24.1
  - pandas=2.2.2
  - pandoc=3.5
  - pandocfilters=1.5.0
  - pango=1.54.0
  - parso=0.8.4
  - patsy=0.5.6
  - pcre2=10.44
  - perl=5.32.1
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.0.0
  - pip=24.3.1
  - pixman=0.43.2
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.6
  - prometheus_client=0.21.0
  - prompt-toolkit=3.0.48
  - prompt_toolkit=3.0.48
  - protobuf=4.25.3
  - psutil=6.1.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pybind11-abi=4
  - pycparser=2.22
  - pygments=2.18.0
  - pynndescent=0.5.13
  - pyparsing=3.2.0
  - pyro-api=0.1.2
  - pyro-ppl=1.9.1
  - pysocks=1.7.1
  - python=3.11.10
  - python-annoy=1.17.3
  - python-dateutil=2.9.0
  - python-fastjsonschema=2.20.0
  - python-igraph=0.11.6
  - python-json-logger=2.0.7
  - python-tzdata=2024.2
  - python_abi=3.11
  - pytorch=2.4.1
  - pytorch-lightning=2.4.0
  - pytz=2024.2
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - qhull=2020.2
  - r-abind=1.4_5
  - r-askpass=1.2.1
  - r-assertthat=0.2.1
  - r-backports=1.5.0
  - r-base=4.3.3
  - r-base64enc=0.1_3
  - r-bh=1.84.0_0
  - r-bit=4.5.0
  - r-bit64=4.5.2
  - r-bitops=1.0_9
  - r-blob=1.2.4
  - r-broom=1.0.7
  - r-bslib=0.8.0
  - r-cachem=1.1.0
  - r-callr=3.7.6
  - r-catools=1.18.3
  - r-cellranger=1.1.0
  - r-checkmate=2.3.2
  - r-cli=3.6.3
  - r-clipr=0.8.0
  - r-cluster=2.1.6
  - r-clustree=0.5.1
  - r-codetools=0.2_20
  - r-colorspace=2.1_1
  - r-commonmark=1.9.2
  - r-conflicted=1.2.0
  - r-cowplot=1.1.3
  - r-cpp11=0.5.0
  - r-crayon=1.5.3
  - r-crosstalk=1.2.1
  - r-curl=5.2.1
  - r-data.table=1.15.4
  - r-dbi=1.2.3
  - r-dbplyr=2.5.0
  - r-deldir=2.0_4
  - r-digest=0.6.37
  - r-dotcall64=1.2
  - r-doubletfinder=2.0.4
  - r-dplyr=1.1.4
  - r-dqrng=0.3.2
  - r-dtplyr=1.3.1
  - r-ellipsis=0.3.2
  - r-evaluate=1.0.1
  - r-fansi=1.0.6
  - r-farver=2.1.2
  - r-fastdummies=1.7.4
  - r-fastmap=1.2.0
  - r-fields=16.3
  - r-fitdistrplus=1.2_1
  - r-fnn=1.1.4.1
  - r-fontawesome=0.5.2
  - r-forcats=1.0.0
  - r-formatr=1.14
  - r-fs=1.6.5
  - r-futile.logger=1.4.3
  - r-futile.options=1.0.1
  - r-future=1.34.0
  - r-future.apply=1.11.2
  - r-gargle=1.5.2
  - r-generics=0.1.3
  - r-ggforce=0.4.2
  - r-ggplot2=3.5.1
  - r-ggraph=2.2.1
  - r-ggrepel=0.9.6
  - r-ggridges=0.5.6
  - r-globals=0.16.3
  - r-glue=1.8.0
  - r-goftest=1.2_3
  - r-googledrive=2.1.1
  - r-googlesheets4=1.1.1
  - r-gplots=3.2.0
  - r-graphlayouts=1.2.0
  - r-gridextra=2.3
  - r-gtable=0.3.6
  - r-gtools=3.9.5
  - r-haven=2.5.4
  - r-here=1.0.1
  - r-hexbin=1.28.4
  - r-hgnchelper=0.8.14
  - r-highr=0.11
  - r-hms=1.1.3
  - r-htmltools=0.5.8.1
  - r-htmlwidgets=1.6.4
  - r-httpuv=1.6.15
  - r-httr=1.4.7
  - r-ica=1.0_3
  - r-ids=1.0.1
  - r-igraph=2.0.3
  - r-irlba=2.3.5.1
  - r-isoband=0.2.7
  - r-jquerylib=0.1.4
  - r-jsonlite=1.8.9
  - r-kernsmooth=2.23_24
  - r-knitr=1.48
  - r-labeling=0.4.3
  - r-lambda.r=1.2.4
  - r-later=1.3.2
  - r-lattice=0.22_6
  - r-lazyeval=0.2.2
  - r-leiden=0.4.3.1
  - r-lifecycle=1.0.4
  - r-listenv=0.9.1
  - r-lmtest=0.9_40
  - r-lubridate=1.9.3
  - r-magrittr=2.0.3
  - r-maps=3.4.2
  - r-mass=7.3_60.0.1
  - r-matrix=1.6_5
  - r-matrixstats=1.4.1
  - r-memoise=2.0.1
  - r-mgcv=1.9_1
  - r-mime=0.12
  - r-miniui=0.1.1.1
  - r-modelr=0.1.11
  - r-munsell=0.5.1
  - r-nlme=3.1_165
  - r-openssl=2.2.2
  - r-openxlsx=4.2.7.1
  - r-parallelly=1.38.0
  - r-patchwork=1.3.0
  - r-pbapply=1.7_2
  - r-pillar=1.9.0
  - r-pkgconfig=2.0.3
  - r-plotly=4.10.4
  - r-plyr=1.8.9
  - r-png=0.1_8
  - r-polyclip=1.10_7
  - r-prettyunits=1.2.0
  - r-processx=3.8.4
  - r-progress=1.2.3
  - r-progressr=0.15.0
  - r-promises=1.3.0
  - r-ps=1.8.1
  - r-purrr=1.0.2
  - r-r6=2.5.1
  - r-ragg=1.3.3
  - r-rann=2.6.2
  - r-rappdirs=0.3.3
  - r-rcolorbrewer=1.1_3
  - r-rcpp=1.0.13
  - r-rcppannoy=0.0.22
  - r-rcpparmadillo=14.0.2_1
  - r-rcppeigen=0.3.4.0.2
  - r-rcpphnsw=0.6.0
  - r-rcppprogress=0.4.2
  - r-rcpptoml=0.2.2
  - r-rcurl=1.98_1.16
  - r-readr=2.1.5
  - r-readxl=1.4.3
  - r-rematch=2.0.0
  - r-rematch2=2.1.2
  - r-reprex=2.1.1
  - r-reshape2=1.4.4
  - r-reticulate=1.39.0
  - r-rlang=1.1.4
  - r-rmarkdown=2.28
  - r-rocr=1.0_11
  - r-rprojroot=2.0.4
  - r-rspectra=0.16_2
  - r-rstudioapi=0.17.1
  - r-rtsne=0.17
  - r-rvest=1.0.4
  - r-sass=0.4.9
  - r-scales=1.3.0
  - r-scattermore=1.2
  - r-sctransform=0.4.1
  - r-selectr=0.4_2
  - r-seurat=5.1.0
  - r-seuratobject=5.0.2
  - r-shiny=1.9.1
  - r-sitmo=2.0.2
  - r-snow=0.4_4
  - r-sourcetools=0.1.7_1
  - r-sp=2.1_4
  - r-spam=2.11_0
  - r-spatstat.data=3.1_2
  - r-spatstat.explore=3.2_6
  - r-spatstat.geom=3.2_9
  - r-spatstat.random=3.2_3
  - r-spatstat.sparse=3.1_0
  - r-spatstat.utils=3.1_0
  - r-splitstackshape=1.4.8
  - r-stringi=1.8.4
  - r-stringr=1.5.1
  - r-survival=3.7_0
  - r-sys=3.4.3
  - r-systemfonts=1.1.0
  - r-tensor=1.5
  - r-textshaping=0.4.0
  - r-tibble=3.2.1
  - r-tidygraph=1.3.0
  - r-tidyr=1.3.1
  - r-tidyselect=1.2.1
  - r-tidyverse=2.0.0
  - r-timechange=0.3.0
  - r-tinytex=0.53
  - r-tweenr=2.0.3
  - r-tzdb=0.4.0
  - r-utf8=1.2.4
  - r-uuid=1.2_1
  - r-uwot=0.1.16
  - r-vctrs=0.6.5
  - r-viridis=0.6.5
  - r-viridislite=0.4.2
  - r-vroom=1.6.5
  - r-withr=3.0.2
  - r-xfun=0.48
  - r-xml2=1.3.6
  - r-xtable=1.8_4
  - r-yaml=2.3.10
  - r-zip=2.3.1
  - r-zoo=1.8_12
  - rav1e=0.6.6
  - re2=2023.09.01
  - readline=8.2
  - referencing=0.35.1
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rich=13.9.3
  - rpds-py=0.20.0
  - rpy2=3.5.11
  - scanpy=1.10.3
  - scikit-learn=1.5.2
  - scikit-misc=0.1.4
  - scipy=1.14.1
  - scvi-tools=1.2.0
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - sed=4.8
  - send2trash=1.8.3
  - session-info=1.0.0
  - setuptools=75.3.0
  - simplegeneric=0.8.1
  - six=1.16.0
  - sleef=3.7
  - snappy=1.2.1
  - sniffio=1.3.1
  - soupsieve=2.5
  - sparse=0.15.4
  - stack_data=0.6.2
  - statsmodels=0.14.4
  - stdlib-list=0.11.0
  - svt-av1=2.3.0
  - sympy=1.13.3
  - sysroot_linux-64=2.17
  - tbb=2021.13.0
  - tensorboard=2.18.0
  - tensorboard-data-server=0.7.0
  - tensorstore=0.1.65
  - terminado=0.18.1
  - texttable=1.7.0
  - threadpoolctl=3.5.0
  - tinycss2=1.4.0
  - tk=8.6.13
  - tktable=2.10
  - toml=0.10.2
  - tomli=2.0.2
  - tomlkit=0.13.2
  - toolz=1.0.0
  - torchmetrics=1.5.1
  - tornado=6.4.1
  - tqdm=4.66.6
  - traitlets=5.14.3
  - types-python-dateutil=2.9.0.20241003
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - typing_utils=0.1.0
  - tzdata=2024b
  - tzlocal=5.2
  - umap-learn=0.5.7
  - unicodedata2=15.1.0
  - uri-template=1.3.0
  - urllib3=2.2.3
  - wcwidth=0.2.13
  - webcolors=24.8.0
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - werkzeug=3.1.0
  - wheel=0.44.0
  - widgetsnbextension=4.0.13
  - xarray=2024.10.0
  - xmltodict=0.14.2
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.10
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxrender=0.9.11
  - xorg-libxt=1.3.0
  - xorg-xorgproto=2024.1
  - xz=5.2.6
  - yaml=0.2.5
  - yq=3.4.3
  - zeromq=4.3.5
  - zipp=3.20.2
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.6
